/* AUTO-GENERIERT aus DTG-Ländertabelle 2025 (Stand Juni 2025). Nicht von Hand bearbeiten. */
/* s: DTG-Empfehlung je Land (P=Chemoprophylaxe in Hochrisikogebieten, NSB=Notfallselbstbehandlung/Standby, EP=nur Expositionsprophylaxe); sp: Erreger; se: Saison. Regionale Unterschiede werden mit dem Patienten besprochen. */
const MALARIA_STAND = "DTG-Ländertabelle 2025 (Stand Juni 2025)";
const MALARIA_DATA = {
  "AF":{"s":"P","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "AO":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "BD":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "BF":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "BI":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "BJ":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "BN":{"s":"EP","sp":"P. knowlesi","se":"Ganzjährig"},
  "BO":{"s":"P","sp":"P. vivax, P. falciparum","se":"Ganzjähig"},
  "BR":{"s":"P","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "BT":{"s":"EP","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "BW":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "BZ":{"s":"EP","sp":"","se":"Ganzjährig"},
  "CD":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "CF":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "CG":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "CI":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "CM":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "CO":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "CR":{"s":"NSB","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "DJ":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "DO":{"s":"NSB","sp":"P. falciparum","se":"Ganzjährig"},
  "EC":{"s":"NSB","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "EH":{"s":"EP","sp":"","se":"Ganzjährig"},
  "ER":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "ET":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "GA":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "GF":{"s":"NSB","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "GH":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "GM":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "GN":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "GQ":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "GT":{"s":"EP","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "GW":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "GY":{"s":"P","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "HN":{"s":"P","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "HT":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "ID":{"s":"P","sp":"P. falciparum, P. vivax, P. knowlesi","se":"Ganzjährig"},
  "IN":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "IQ":{"s":"EP","sp":"","se":"Mai–November"},
  "IR":{"s":"NSB","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "KE":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "KH":{"s":"NSB","sp":"P. falciparum, P. vivax, P. knowlesi","se":"Ganzjährig"},
  "KM":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "KP":{"s":"EP","sp":"P. vivax","se":"Malariasaison"},
  "KR":{"s":"EP","sp":"P. vivax","se":"Januar–Februar"},
  "LA":{"s":"NSB","sp":"P. vivax, P. falciparum, P. knowlesi","se":"Ganzjährig"},
  "LR":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "MG":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "ML":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "MM":{"s":"NSB","sp":"P. vivax, P. falciparum, P. knowlesi","se":"Ganzjährig"},
  "MR":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "MW":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "MX":{"s":"EP","sp":"P. vivax","se":"Ganzjährig"},
  "MY":{"s":"NSB","sp":"P. knowlesi","se":"Ganzjährig"},
  "MZ":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "NA":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "NE":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "NG":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "NI":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "NP":{"s":"EP","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "PA":{"s":"NSB","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "PE":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "PG":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "PH":{"s":"P","sp":"P. falciparum, P. vivax, P. knowlesi","se":"Ganzjährig"},
  "PK":{"s":"P","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "RW":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "SB":{"s":"P","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "SD":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "SL":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "SN":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "SO":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "SS":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "ST":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "SY":{"s":"EP","sp":"P. vivax","se":"Mai–Oktober"},
  "SZ":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "TD":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "TG":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "TH":{"s":"NSB","sp":"P. vivax, P. falciparum, P. knowlesi","se":"Ganzjährig"},
  "TZ":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "UG":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "VE":{"s":"P","sp":"P. vivax, P. falciparum","se":"Ganzjährig"},
  "VN":{"s":"EP","sp":"P. vivax, P. falciparum, P. knowlesi","se":"Ganzjährig"},
  "VU":{"s":"NSB","sp":"P. vivax","se":"Ganzjährig"},
  "YE":{"s":"P","sp":"P. falciparum, P. vivax","se":"Ganzjährig"},
  "YT":{"s":"EP","sp":"P. falciparum","se":"Ganzjährig"},
  "ZA":{"s":"NSB","sp":"P. falciparum","se":"Ganzjährig"},
  "ZM":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"},
  "ZW":{"s":"P","sp":"P. falciparum","se":"Ganzjährig"}
};
if (typeof module !== "undefined" && module.exports) { module.exports = { MALARIA_DATA, MALARIA_STAND }; }
